SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


DROP SCHEMA IF EXISTS `web3_db` ;


CREATE SCHEMA IF NOT EXISTS `web3_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `web3_db` ;


DROP TABLE IF EXISTS `web3_db`.`wallets` ;

CREATE TABLE IF NOT EXISTS `web3_db`.`wallets` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(42) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `nonce` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `address` (`address` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


DROP TABLE IF EXISTS `web3_db`.`users` ;

CREATE TABLE IF NOT EXISTS `web3_db`.`users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `wallet_id` BIGINT NOT NULL,
  `username` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `telegram_user_id` BIGINT NULL DEFAULT NULL,
  `avatar_url` VARCHAR(500) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `bio` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `is_active` TINYINT(1) NULL DEFAULT '1',
  `last_login_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  INDEX `wallet_id` (`wallet_id` ASC) VISIBLE,
  CONSTRAINT `users_ibfk_1`
    FOREIGN KEY (`wallet_id`)
    REFERENCES `web3_db`.`wallets` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


DROP TABLE IF EXISTS `web3_db`.`ERC20` ;

CREATE TABLE IF NOT EXISTS `web3_db`.`ERC20` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name_token` VARCHAR(45) NULL,
  `address` VARCHAR(42) NOT NULL,
  `currency` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY address (`address`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE users
  ADD CONSTRAINT users_ibfk_1 FOREIGN KEY (`wallet_id`) REFERENCES wallets (`id`);

ALTER TABLE wallets
  ADD COLUMN nonce varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL;